# Generated by Django 2.2.6 on 2019-12-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tea',
            name='stores',
        ),
        migrations.AddField(
            model_name='tea',
            name='stores',
            field=models.ManyToManyField(to='main_app.Store'),
        ),
    ]
