# Generated by Django 2.2.6 on 2019-12-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191220_0129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinking',
            options={'ordering': ['-date']},
        ),
    ]
